-- Sign-in tables for this deployment's own OAuth 2.1 authorization server.
--
-- Every name carries an `icloud_` prefix. The sibling YNAB deployment keeps its
-- own unprefixed set in this same database, and the two cannot share them: each
-- deployment signs its tokens with its own BETTER_AUTH_SECRET, and the signing
-- keys in the jwks table are encrypted with it, so whichever wrote last would
-- lock the other out.
--
-- Generated by Better Auth 1.7.5 (`npm run auth:migrate`) and captured here so
-- the schema is reviewable and repeatable rather than only existing wherever
-- the tool was last pointed.

CREATE TABLE public.icloud_account (
    id text NOT NULL,
    "accountId" text NOT NULL,
    "providerId" text NOT NULL,
    "userId" text NOT NULL,
    "accessToken" text,
    "refreshToken" text,
    "idToken" text,
    "accessTokenExpiresAt" timestamp with time zone,
    "refreshTokenExpiresAt" timestamp with time zone,
    scope text,
    password text,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL
);

CREATE TABLE public.icloud_jwks (
    id text NOT NULL,
    "publicKey" text NOT NULL,
    "privateKey" text NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "expiresAt" timestamp with time zone,
    alg text,
    crv text
);

CREATE TABLE public."icloud_oauthAccessToken" (
    id text NOT NULL,
    token text NOT NULL,
    "clientId" text NOT NULL,
    "sessionId" text,
    "userId" text,
    "referenceId" text,
    "authorizationCodeId" text,
    resources jsonb,
    "requestedUserInfoClaims" jsonb,
    "refreshId" text,
    "expiresAt" timestamp with time zone NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    revoked timestamp with time zone,
    confirmation jsonb,
    scopes jsonb NOT NULL
);

CREATE TABLE public."icloud_oauthClient" (
    id text NOT NULL,
    "clientId" text NOT NULL,
    "clientSecret" text,
    "clientDiscoveryId" text,
    disabled boolean,
    "skipConsent" boolean,
    "enableEndSession" boolean,
    "subjectType" text,
    scopes jsonb,
    "clientCredentialsScopes" jsonb,
    "userId" text,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    name text,
    uri text,
    icon text,
    contacts jsonb,
    tos text,
    policy text,
    "softwareId" text,
    "softwareVersion" text,
    "softwareStatement" text,
    "redirectUris" jsonb NOT NULL,
    "postLogoutRedirectUris" jsonb,
    "backchannelLogoutUri" text,
    "backchannelLogoutSessionRequired" boolean,
    "tokenEndpointAuthMethod" text,
    "applicationType" text,
    jwks text,
    "jwksUri" text,
    "grantTypes" jsonb,
    "responseTypes" jsonb,
    "requirePKCE" boolean,
    "dpopBoundAccessTokens" boolean,
    "referenceId" text,
    metadata jsonb
);

CREATE TABLE public."icloud_oauthClientAssertion" (
    id text NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL
);

CREATE TABLE public."icloud_oauthClientResource" (
    id text NOT NULL,
    "clientId" text NOT NULL,
    "resourceId" text NOT NULL,
    metadata jsonb,
    "createdAt" timestamp with time zone
);

CREATE TABLE public."icloud_oauthConsent" (
    id text NOT NULL,
    "clientId" text NOT NULL,
    "userId" text,
    "referenceId" text,
    resources jsonb,
    "requestedUserInfoClaims" jsonb,
    scopes jsonb NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL
);

CREATE TABLE public."icloud_oauthRefreshToken" (
    id text NOT NULL,
    token text NOT NULL,
    "clientId" text NOT NULL,
    "sessionId" text,
    "userId" text NOT NULL,
    "referenceId" text,
    "authorizationCodeId" text,
    resources jsonb,
    "requestedUserInfoClaims" jsonb,
    "expiresAt" timestamp with time zone NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    revoked timestamp with time zone,
    "rotatedAt" timestamp with time zone,
    "rotationReplayResponse" text,
    "rotationReplayExpiresAt" timestamp with time zone,
    "authTime" timestamp with time zone,
    confirmation jsonb,
    scopes jsonb NOT NULL
);

CREATE TABLE public."icloud_oauthResource" (
    id text NOT NULL,
    identifier text NOT NULL,
    name text NOT NULL,
    "accessTokenTtl" integer,
    "refreshTokenTtl" integer,
    "signingAlgorithm" text,
    "signingKeyId" text,
    "allowedScopes" jsonb,
    "customClaims" jsonb,
    "dpopBoundAccessTokensRequired" boolean,
    disabled boolean,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    "policyVersion" integer,
    metadata jsonb
);

CREATE TABLE public.icloud_passkey (
    id text NOT NULL,
    name text,
    "publicKey" text NOT NULL,
    "userId" text NOT NULL,
    "credentialID" text NOT NULL,
    counter integer NOT NULL,
    "deviceType" text NOT NULL,
    "backedUp" boolean NOT NULL,
    transports text,
    "createdAt" timestamp with time zone,
    aaguid text
);

CREATE TABLE public.icloud_session (
    id text NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    token text NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "ipAddress" text,
    "userAgent" text,
    "userId" text NOT NULL
);

CREATE TABLE public.icloud_user (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    "emailVerified" boolean NOT NULL,
    image text,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.icloud_verification (
    id text NOT NULL,
    identifier text NOT NULL,
    value text NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE ONLY public.icloud_account
    ADD CONSTRAINT icloud_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.icloud_jwks
    ADD CONSTRAINT icloud_jwks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public."icloud_oauthAccessToken"
    ADD CONSTRAINT "icloud_oauthAccessToken_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."icloud_oauthAccessToken"
    ADD CONSTRAINT "icloud_oauthAccessToken_token_key" UNIQUE (token);

ALTER TABLE ONLY public."icloud_oauthClientAssertion"
    ADD CONSTRAINT "icloud_oauthClientAssertion_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."icloud_oauthClientResource"
    ADD CONSTRAINT "icloud_oauthClientResource_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."icloud_oauthClient"
    ADD CONSTRAINT "icloud_oauthClient_clientId_key" UNIQUE ("clientId");

ALTER TABLE ONLY public."icloud_oauthClient"
    ADD CONSTRAINT "icloud_oauthClient_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."icloud_oauthConsent"
    ADD CONSTRAINT "icloud_oauthConsent_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."icloud_oauthRefreshToken"
    ADD CONSTRAINT "icloud_oauthRefreshToken_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."icloud_oauthRefreshToken"
    ADD CONSTRAINT "icloud_oauthRefreshToken_token_key" UNIQUE (token);

ALTER TABLE ONLY public."icloud_oauthResource"
    ADD CONSTRAINT "icloud_oauthResource_identifier_key" UNIQUE (identifier);

ALTER TABLE ONLY public."icloud_oauthResource"
    ADD CONSTRAINT "icloud_oauthResource_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public.icloud_passkey
    ADD CONSTRAINT icloud_passkey_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.icloud_session
    ADD CONSTRAINT icloud_session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.icloud_session
    ADD CONSTRAINT icloud_session_token_key UNIQUE (token);

ALTER TABLE ONLY public.icloud_user
    ADD CONSTRAINT icloud_user_email_key UNIQUE (email);

ALTER TABLE ONLY public.icloud_user
    ADD CONSTRAINT icloud_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.icloud_verification
    ADD CONSTRAINT icloud_verification_pkey PRIMARY KEY (id);

CREATE INDEX "icloud_account_userId_idx" ON public.icloud_account USING btree ("userId");

CREATE INDEX "icloud_oauthAccessToken_authorizationCodeId_idx" ON public."icloud_oauthAccessToken" USING btree ("authorizationCodeId");

CREATE INDEX "icloud_oauthAccessToken_clientId_idx" ON public."icloud_oauthAccessToken" USING btree ("clientId");

CREATE INDEX "icloud_oauthAccessToken_refreshId_idx" ON public."icloud_oauthAccessToken" USING btree ("refreshId");

CREATE INDEX "icloud_oauthAccessToken_sessionId_idx" ON public."icloud_oauthAccessToken" USING btree ("sessionId");

CREATE INDEX "icloud_oauthAccessToken_userId_idx" ON public."icloud_oauthAccessToken" USING btree ("userId");

CREATE INDEX "icloud_oauthClientResource_clientId_idx" ON public."icloud_oauthClientResource" USING btree ("clientId");

CREATE UNIQUE INDEX "icloud_oauthClientResource_clientId_resourceId_uidx" ON public."icloud_oauthClientResource" USING btree ("clientId", "resourceId");

CREATE INDEX "icloud_oauthClientResource_resourceId_idx" ON public."icloud_oauthClientResource" USING btree ("resourceId");

CREATE INDEX "icloud_oauthClient_userId_idx" ON public."icloud_oauthClient" USING btree ("userId");

CREATE INDEX "icloud_oauthConsent_clientId_idx" ON public."icloud_oauthConsent" USING btree ("clientId");

CREATE INDEX "icloud_oauthConsent_userId_idx" ON public."icloud_oauthConsent" USING btree ("userId");

CREATE INDEX "icloud_oauthRefreshToken_authorizationCodeId_idx" ON public."icloud_oauthRefreshToken" USING btree ("authorizationCodeId");

CREATE INDEX "icloud_oauthRefreshToken_clientId_idx" ON public."icloud_oauthRefreshToken" USING btree ("clientId");

CREATE INDEX "icloud_oauthRefreshToken_sessionId_idx" ON public."icloud_oauthRefreshToken" USING btree ("sessionId");

CREATE INDEX "icloud_oauthRefreshToken_userId_idx" ON public."icloud_oauthRefreshToken" USING btree ("userId");

CREATE INDEX "icloud_passkey_credentialID_idx" ON public.icloud_passkey USING btree ("credentialID");

CREATE INDEX "icloud_passkey_userId_idx" ON public.icloud_passkey USING btree ("userId");

CREATE INDEX "icloud_session_userId_idx" ON public.icloud_session USING btree ("userId");

CREATE INDEX icloud_verification_identifier_idx ON public.icloud_verification USING btree (identifier);

ALTER TABLE ONLY public.icloud_account
    ADD CONSTRAINT "icloud_account_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.icloud_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthAccessToken"
    ADD CONSTRAINT "icloud_oauthAccessToken_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES public."icloud_oauthClient"("clientId") ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthAccessToken"
    ADD CONSTRAINT "icloud_oauthAccessToken_refreshId_fkey" FOREIGN KEY ("refreshId") REFERENCES public."icloud_oauthRefreshToken"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthAccessToken"
    ADD CONSTRAINT "icloud_oauthAccessToken_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES public.icloud_session(id) ON DELETE SET NULL;

ALTER TABLE ONLY public."icloud_oauthAccessToken"
    ADD CONSTRAINT "icloud_oauthAccessToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.icloud_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthClientResource"
    ADD CONSTRAINT "icloud_oauthClientResource_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES public."icloud_oauthClient"("clientId") ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthClientResource"
    ADD CONSTRAINT "icloud_oauthClientResource_resourceId_fkey" FOREIGN KEY ("resourceId") REFERENCES public."icloud_oauthResource"(identifier) ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthClient"
    ADD CONSTRAINT "icloud_oauthClient_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.icloud_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthConsent"
    ADD CONSTRAINT "icloud_oauthConsent_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES public."icloud_oauthClient"("clientId") ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthConsent"
    ADD CONSTRAINT "icloud_oauthConsent_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.icloud_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthRefreshToken"
    ADD CONSTRAINT "icloud_oauthRefreshToken_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES public."icloud_oauthClient"("clientId") ON DELETE CASCADE;

ALTER TABLE ONLY public."icloud_oauthRefreshToken"
    ADD CONSTRAINT "icloud_oauthRefreshToken_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES public.icloud_session(id) ON DELETE SET NULL;

ALTER TABLE ONLY public."icloud_oauthRefreshToken"
    ADD CONSTRAINT "icloud_oauthRefreshToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.icloud_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.icloud_passkey
    ADD CONSTRAINT "icloud_passkey_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.icloud_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.icloud_session
    ADD CONSTRAINT "icloud_session_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.icloud_user(id) ON DELETE CASCADE;

-- Row level security is switched on with no policies at all, which denies every
-- request that it applies to. The server connects as the table owner and so
-- bypasses it entirely, while Supabase's public REST API, which does not, is
-- left with no way to read a single row. Without this, anyone holding the
-- project's publishable key could read the sign-in tables over HTTP.
ALTER TABLE public.icloud_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.icloud_jwks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."icloud_oauthAccessToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."icloud_oauthClient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."icloud_oauthClientAssertion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."icloud_oauthClientResource" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."icloud_oauthConsent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."icloud_oauthRefreshToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."icloud_oauthResource" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.icloud_passkey ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.icloud_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.icloud_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.icloud_verification ENABLE ROW LEVEL SECURITY;
